module.exports = {
  cliCommands: {
    adddependencies: 'adddependencies',
    deploy: 'deploy',
    importbundle: 'importbundle',
    importconfiguration: 'importconfiguration',
    importfiles: 'importfiles',
    importobjects: 'importobjects',
    listbundles: 'listbundles',
    listconfiguration: 'listconfiguration',
    listfiles: 'listfiles',
    listmissingdependencies: 'listmissingdependencies',
    listobjects: 'listobjects',
    preview: 'preview',
    project: 'project',
    update: 'update',
    updatecustomrecordwithinstances: 'updatecustomrecordwithinstances',
    validate: 'validate',
  },
};
